COINES_INSTALL_PATH ?= ../../../..

EXAMPLE_FILE ?= pressure.c

API_LOCATION ?= ../..

C_SRCS += \
$(API_LOCATION)/bme280.c \
../common/common.c

INCLUDEPATHS += \
$(API_LOCATION) \
../common

include $(COINES_INSTALL_PATH)/coines.mk